name: Compilar APK Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar con Gradle Build Tool
        uses: gradle/actions/setup-gradle@v3

      - name: Generar APK en modo Debug
        run: gradle assembleDebug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
